# coding: gbk


def datalib_format():
    return dict(
        gen=['par_no', 'xd', 'xdp', 'xdpp', 'xq', 'xqp', 'xqpp', 'x2',
             'ra', 'td0p', 'td0pp', 'tq0p', 'tq0pp', 'tj', 'a', 'b', 'n',
             'd_sec', 'note'],
        avr1=['par_no', 'k_measure', 'k_amplify', 'k_feed', 'efd_max',
              'efd_min', 't_measure', 't_amplify', 't_feed', 't_exciter',
              'note'],
        avr2=['par_no', 'k_measure', 'k_amplify', 'k_type', 'vt_max',
              'vt_min', 'k_voltage', 'k_current', 'k_arc', 'efd_max',
              'efd_min', 't_measure', 't_amplify', 't1', 't2', 't3', 't4',
              'note'],
        gov1=['par_no', 'k_measure', 'regu_ratio', 'k_sfeed',
              'valve_max', 'valve_min', 'gate_max', 'gate_min',
              'dead_range', 'k_overheat', 't_sfeed', 't_service',
              'tw_hydro', 't0_steam', 't_overheat', 'note'],
        moto=['par_no', 'r_rotator', 'x_coil', 'x_rotator', 'k_damp',
              'p_damp', 's0_slip', 't1_rotator', 't2_rotator', 'fp',
              'fq', 'note'],
        svc1=['par_no', 'k_amplify', 'db_max', 'db_min', 'b_max',
              'b_min', 't_amplify', 't_measure', 't_rectifier', 'note'],
        svc2=['par_no', 'x_reactor', 't_lag', 'x_capacity', 'i_overload',
              'note'],
        pss1=['par_no', 'k_rotate', 'k_power', 'k_voltage', 'k_type',
              'vs_max', 'vs_min', 't_washout', 't1_shift', 't2_shift',
              't3_shift', 't4_shift', 'note'],
        load=['par_no', 'ap', 'bp', 'cp', 'fp', 'np', 'aq', 'bq', 'cq',
              'fq', 'nq', 'note'],
        dc=['par_no', 'tmp1', 'tmp2', 't1_regulat', 't2_regulat',
            't3_regulat', 'k_amplify', 'note'],
        avr310=['par_no', 'xc_modul', 'tr_measure', 'k_dcplus',
                'kv_integ', 't1_series', 't2_series', 't3_series',
                't4_series', 'ka_amplify', 'ta_amplify', 'vamax',
                'vamin', 'kf_paral', 'tf_paral', 'kh1_feed', 'kb_adjust',
                't5_adjust', 'vrmax', 'vrmin', 'ke_exciter', 'te_exciter',
                'vemax', 'c1_exciter', 'c2_exciter', 'kc_load',
                'kd_exciter', 'efdmax', 'r_model', 'vmax1', 'vmin1',
                'vmax2', 'vmin2', 'lelocation', 'lemodel', 'leparno',
                'oelocation', 'oemodel', 'oeparno', 'oilocation',
                'oimodel', 'oiparno', 'note'],
        avr1112=['par_no', 'xc_modul', 'tr_measure', 'k_dcplus',
                 'kv_integ', 't1_series', 't2_series', 't3_series',
                 't4_series', 'ka_amplify', 'ta_amplify', 'vamax',
                 'vamin', 'kf_paral', 'tf_paral', 'vrmax', 'vrmin',
                 'kc_load', 'vs_pos', 'r_model', 'vmax1', 'vmin1',
                 'vmax2', 'vmin2', 'lelocation', 'lemodel', 'leparno',
                 'oelocation', 'oemodel', 'oeparno', 'oilocation',
                 'oimodel', 'oiparno', 'note'],
        pss2=['par_no', 'k_rotate', 'k_power', 'k_voltage', 't_measure',
              't_washout1', 't_washout2', 't1_shift', 't2_shift',
              't3_shift', 't4_shift', 't5_shift', 't6_shift', 'vs_max',
              'vs_min', 'note'],
        cload=['par_no', 'r1', 'x1', 'xm', 'r2', 'x2', 'tj', 'a',
               'b', 'kpm', 'mlf', 'p_z', 'p_i', 'q_z', 'q_i', 'note'],
        dload=['par_no', 'rank', 'a1', 'a2', 'b0', 'b1', 'b2', 'a1p',
               'a2p', 'b0p', 'b1p', 'b2p', 'note'],
        pss3=['par_no', 'kp', 'k0p', 'k1p', 'k2p', 'k3p', 'td',
              't1_shift', 't2_shift', 't3_shift', 'vs_max', 'vs_min',
              'tacc', 'macc', 'nacc', 'iacc', 'ktype', 'k4p',
              't4_shift', 'note'],
        gov2=['par_no', 'k_rev', 'death', 'tr', 'tb', 'topen', 'tc',
              'velc', 'velo', 'pmax', 'pmin', 'tch', 'fhp', 'trh', 'fip',
              'tco', 'flp', 'lnd', 'tsh', 'td', 'tw', 'k_mp', 'tdly',
              'vmax', 'vmin', 'note'],
        gov3=['par_no', 'death', 'k_rev', 't1', 'kmld', 'kp1', 'kd1',
              'ki1', 'imax1', 'imin1', 'pmax1', 'pmin1', 'kmldf', 'ffmax',
              'ffmin', 'kmap', 'kp2', 'kd2', 'ki2', 'imax2', 'imin2',
              'pmax2', 'pmin2', 'cmax', 'cmin', 'tc', 'topen', 'velc',
              'velo', 'pmax', 'pmin', 'tf', 'kp', 'kd', 'ki', 'imax',
              'imin', 'pidmax', 'pidmin', 'tch', 'fhp', 'trh', 'fip',
              'tco', 'flp', 'lnd', 'tsh', 'td', 'tw', 'k_mp', 'tdly',
              'vmax', 'vmin', 't4', 'note'],
        gov4=['par_no', 't1', 'death', 'k_rev', 'kmct', 'kp1', 'kd1',
              'ki1', 'imax1', 'imin1', 'pmax1', 'pmin1', 'k2', 'ffmax',
              'ffmin', 'tc', 'topen', 'velc', 'velo', 'pmax',
              'pmin', 'tf', 'kp', 'kd', 'ki', 'imax', 'imin', 'pidmax',
              'pidmin', 'tch', 'fhp', 'trh', 'fip', 'tco', 'flp', 'lnd',
              'tsh', 'td', 'tw', 'k_mp', 'tdly', 'vmax', 'vmin', 't4',
              'note'],
        gov5=['par_no', 't_lb', 'death', 'kmlb', 'k1', 'k2', 'kmct',
              'kp1', 'kd1', 'ki1', 'imax1', 'imin1', 'pmax1', 'pmin1',
              'ffmax', 'ffmin', 'tc', 'topen', 'velc', 'velo', 'pmax',
              'pmin', 'tf', 'kp', 'kd', 'ki', 'imax', 'imin', 'pidmax',
              'pidmin', 'tch', 'fhp', 'trh', 'fip', 'tco', 'flp', 'lnd',
              'tsh', 'td', 'tw', 'k_mp', 'tdly', 'vmax', 'vmin',
              't4', 'note'],
        svc3=['par_no', 'ts1', 'vemax', 'ts2', 'ts3', 'a', 'b', 'ts4',
              'ts5', 'ksvs', 'ksd', 'bmax', 'bmaxp', 'bminp', 'bmin',
              'ts6', 'dv', 'ks1', 'ts7', 'ts8', 'ts9', 'ap', 'bp',
              'ts13', 'ts14', 'ts15', 'ts16', 'ks3', 'vscsmax', 'ierr',
              'ks2', 'ts10', 'ts11', 'ts12', 'vscsmin', 'note'],
        avr13=['par_no', 'rc', 'xc', 'tr', 'vimax', 'vimin', 'tb', 'tc',
               'ka', 'ta', 'vrmax', 'vrmin', 'kf', 'tf', 'kc', 'efd_max',
               'efd_min', 'note'],
        slm=['par_no', 'rd', 'xd', 'mtype', 's0', 'mlf', 'r1', 'x1',
             'r2', 'x2', 'tj', 'xm', 'a', 'b', 'pfact', 'p_z', 'q_z',
             'p_i', 'q_i', 'fp', 'fq', 'gen_valid', 'gen_p0',
             'gen_q0', 'gen_sn', 'gen_pn', 'gen_model', 'gen_par',
             'avr_model', 'avr_par', 'gov_model', 'gov_par', 'pss_model',
             'pss_par', 'k_sb', 'note'],
        pss4=['par_no', 'trw', 't5', 't6', 't7', 'kr', 'trp', 'tw', 'tw1',
              'tw2', 'ks', 't9', 't10', 't12', 'kw', 'kp', 't1', 't2',
              't13', 't14', 't3', 't4', 'vsmax', 'vsmin', 'note'],
        avr14=['par_no', 'rc', 'xc', 'tr', 'ka', 'ta', 'kp', 'ki',
               'vrmax', 'vrmin', 'ikp', 'iki', 'vfmax', 'vfmin', 'kt',
               'tt', 'kifd', 'tifd', 'efd_max', 'efd_min', 'note'],
        pss5=['par_no', 't1', 't2', 't3', 't4', 't5', 'a', 'p', 'k1',
              't6', 'k2', 'k', 'vsmax', 'vsmin', 'note'],
        tcsc=['par_no', 'kap', 'tap', 'twp', 't1p', 't2p', 't3p', 't4p',
              'kav', 'tav', 'twv', 't1v', 't2v', 't3v', 't4v', 'ta1',
              'tb1', 'kxc01', 'kpp', 'ttcsc', 'x_max', 'x_min',
              'in1', 'ib', 'xc0', 'alfa', 'death_p', 'death_v', 'iquit',
              'tquit', 'iopen', 'topen', 'ta2', 'tb2', 'ta3', 'tb3',
              'ta4', 'tb4', 'ta5', 'tb5', 'mkctrl', 'mkmov', 'capp',
              'maxmove', 'maxmovs', 'iopermax', 'trecon', 'dtrecon',
              'ireconmax', 'dtreconmax', 'mkopenrecon', 'note'],
        wgmot=['par_no', 'gratepower', 'windpower_model', 'a1', 'a2',
               'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'a10', 'a11',
               'a12', 'a13', 'a14', 'a15', 'a16', 'a17', 'a18', 'a19',
               'a20', 'a21', 'a22', 'a23', 'a24', 'a25', 'turbine_radius',
               'axis_flex', 'axis_damp', 'omega_base', 'omega_base_t',
               'tj_turbine', 'tj_gen', 'th', 'rho', 'omega_rate',
               'vwind_ci', 'vwind_co', 'vwind_rate', 'vwind0',
               'turbine_model', 'r2', 'x2', 'x1', 'td01', 'note'],
        wgge=['par_no', 'gratepower', 'windpower_model', 'a1', 'a2',
              'a3', 'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'a10', 'a11',
              'a12', 'a13', 'a14', 'a15', 'a16', 'a17', 'a18', 'a19',
              'a20', 'a21', 'a22', 'a23', 'a24', 'a25', 'turbine_radius',
              'axis_flex', 'axis_damp', 'omega_base', 'omega_base_t',
              'tj_turbine', 'tj_gen', 'th', 'rho', 'omega_rate',
              'vwind_ci', 'vwind_co', 'vwind_rate', 'vwind0',
              'turbine_model', 'kpp', 'kip', 'tp', 'thetamax', 'thetamin',
              'dthetamax', 'dthetamin', 'pmax', 'pmin', 'dpmax', 'dpmin',
              'kpc', 'kic', 'kptrq', 'kitrq', 'tpc', 'tr', 'tv', 'kpv',
              'kiv', 'kqi', 'kvi', 'qmax', 'qmin', 'xiqmax', 'xiqmin',
              'vmax', 'vmin', 'ipmax', 'qmod', 'cosphi', 'tco', 'xpp',
              'rl', 'xl', 'note'],
        wdgen1=['par_no', 'gratepower', 'wtgmodel', 'a1', 'a2', 'a3',
                'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'a10', 'a11', 'a12',
                'a13', 'a14', 'a15', 'a16', 'a17', 'a18', 'a19',
                'a20', 'a21', 'a22', 'a23', 'a24', 'a25',
                'iturbine_radius', 'axis_flex', 'axis_damp', 'omg_base',
                'omg_baset', 'tj_turbine', 'tj_gen', 'th', 'rho',
                'omg_rate', 'vwind_ci', 'vwind_co', 'vwind_rate',
                'vwind0', 'tur_model', 'kpp', 'kip', 'tp', 'thetamax',
                'thetamin', 'dthetamax', 'dthetamin', 'pmax', 'pmin',
                'dpmax', 'dpmin', 'kpc', 'kic', 'kptrq', 'kitrq', 'tpc',
                'tr', 'tv', 'kpv', 'kiv', 'kqi', 'kvi', 'qmax', 'qmin',
                'xiqmax', 'xiqmin', 'vmax', 'vmin', 'ipmax', 'nqmod',
                'cosphi', 'tco', 'xpp', 'rc', 'xc', 'vzerox', 'vbrkpt',
                'pbrkpt', 'rrpwr', 'vl1', 'vl2', 'tl1', 'tl2', 'vh1',
                'vh2', 'th1', 'th2', 'trv', 'fn', 'tc', 'tpwr', 'vermn',
                'vermx', 'vfrz', 'tlpqd', 'kqd', 'xqd', 'tw', 'tpav',
                'apcpa', 'apcpbc', 'apcpd', 'apcfa', 'apcfb', 'apcfc',
                'apcfd', 'apcpmax', 'apcpmin', 'kwi', 'dbwi', 'tlpwi',
                'twowi', 'urlwi', 'drlwi', 'pmxwi', 'pmnwi', 'lphl',
                'lqhl', 'ebst', 'kdbr', 'imaxtd', 'iqmxv0', 'lvrtp',
                'hvrtp', 'nwfflg', 'napcflg', 'npqflag', 'nlvrtflg',
                'nlvplflg', 'nwdinflg', 'nqdroopflg', 'ndbrflg',
                'convertype', 'lvpldt', 'lvplrrt', 'lvplosr', 'lvplddly',
                'lvpludly', 'ipzerox', 'switchiqk', 'switchiin',
                'tvemd', 'tmp1', 'tmp2', 'tmp3', 'tmp4', 'tmp5', 'tmp6',
                'tmp7', 'tmp8', 'tmp9', 'tmp10', 'note'],
        wdgen2=['par_no', 'gratepower', 'wtgmodel', 'a1', 'a2', 'a3',
                'a4', 'a5', 'a6', 'a7', 'a8', 'a9', 'a10', 'a11', 'a12',
                'a13', 'a14', 'a15', 'a16', 'a17', 'a18', 'a19', 'a20',
                'a21', 'a22', 'a23', 'a24', 'a25', 'iturbine_radius',
                'axis_flex', 'axis_damp', 'omg_base', 'omg_baset',
                'tj_turbine', 'tj_gen', 'th', 'rho', 'omg_rate',
                'vwind_ci', 'vwind_co', 'vwind_rate', 'vwind0',
                'tur_model', 'kpp', 'kip', 'tp', 'thetamax', 'thetamin',
                'dthetamax', 'dthetamin', 'pmax', 'pmin', 'dpmax',
                'dpmin', 'kpc', 'kic', 'kptrq', 'kitrq', 'tpc', 'tr',
                'tv', 'kpv', 'kiv', 'kqi', 'kvi', 'qmax', 'qmin', 'xiqmax',
                'xiqmin', 'vmax', 'vmin', 'ipmax', 'nqmod', 'cosphi',
                'tco', 'xpp', 'rc', 'xc', 'vzerox', 'vbrkpt', 'pbrkpt',
                'rrpwr', 'vl1', 'vl2', 'tl1', 'tl2', 'vh1', 'vh2', 'th1',
                'th2', 'trv', 'fn', 'tc', 'tpwr', 'vermn', 'vermx',
                'vfrz', 'tlpqd', 'kqd', 'xqd', 'tw', 'tpav', 'apcpa',
                'apcpbc', 'apcpd', 'apcfa', 'apcfb', 'apcfc', 'apcfd',
                'apcpmax', 'apcpmin', 'kwi', 'dbwi', 'tlpwi', 'twowi',
                'urlwi', 'drlwi', 'pmxwi', 'pmnwi', 'lphl', 'lqhl',
                'ebst', 'kdbr', 'imaxtd', 'iqmxv0', 'lvrtp', 'hvrtp',
                'nwfflg', 'napcflg', 'npqflag', 'nlvrtflg', 'nlvplflg',
                'nwdinflg', 'nqdroopflg', 'ndbrflg', 'convertype',
                'lvpldt', 'lvplrrt', 'lvplosr', 'lvplddly', 'lvpludly',
                'ipzerox', 'switchiqk', 'switchiin', 'tvemd', 'tmp1',
                'tmp2', 'tmp3', 'tmp4', 'tmp5', 'tmp6', 'tmp7', 'tmp8',
                'tmp9', 'tmp10', 'note'],
        csr=['par_no', 'tr', 'kctrl', 'kp2', 'ki2', 'imax2', 'imin2',
             'kp1', 'ki1', 'imax1', 'imin1', 'k4', 'k3', 'kf1', 'tf1',
             'k1', 'k2', 'idmax', 'idmin', 'kf2', 'tf2', 'db',
             'vmax', 'vmin', 'dltat', 'dltai', 'qn', 'x0', 'note'],
        stm=['par_no', 'sbase', 't1', 't2', 't3', 't4', 't5', 'tp', 'ts',
             'kp', 'ki', 'kd', 'xt', 'vmax', 'vmin', 'icmax', 'ilmax',
             'vstandby', 'ks1', 'ts7', 'ts8', 'ts9', 'ap', 'bp', 'ts13',
             'ts14', 'ts15', 'ts16', 'ks3', 'vscsmax', 'ierr', 'ks2',
             'ts10', 'ts11', 'ts12', 'vscsmin', 'note'],
        gov6=['par_no', 'pmax', 'ar', 't1', 't2', 't3', 't4', 't5', 'af',
              'note'],
        ds1=['par_no', 'td1', 'tf1', 'e1', 'a1', 'b1', 'c1', 'd1', 'k1',
             'td2', 'tf2', 'e2',
             'a2', 'b2', 'c2', 'd2', 'k2', 'pmax', 'pmin', 'note'],
        nrpss=['par_no', 'r', 'xdp', 'xq', 'xd', 'tdelay', 'ki', 'kd',
               'kp', 'kpv', 'kiv', 'kdv', 'tj', 'td0p', 'twashout',
               'efdmax', 'efdmin', 'note'],
        gov7=['par_no', 'type1', 'type2', 'type3', 't1', 'tr1', 'db1',
              'db1max', 'db1min', 'kw', 't2', 'tr2', 'ep', 'db2',
              'db2max', 'db2min', 't3', 'tr3', 'bp', 'db3', 'db3max',
              'db3min', 'kp', 'kd', 'ki', 'td', 'intmax', 'intmin',
              'pidmax', 'pidmin', 'yc', 'tclose', 'topen', 'velc',
              'velo', 'pmax', 'pmin', 'tf', 'kp1', 'kd1', 'ki1',
              'intmax1', 'intmin1', 'pidmax1', 'pidmin1', 't4', 'tw',
              'kwtype', 'at', 'tr', 'ynl', 'dbwp', 'dbwn', 'pchoice',
              'promax1', 'promin1', 'promax2', 'promin2', 'ratelimp',
              'ratelimn', 'note'],
        ds2=['par_no', 'trect', 'db1', 't1', 'krect', 'tinv', 'db2',
             't2', 'kinv', 'pmax', 'pmin', 'note'],
        svc4=['par_no', 'k1', 't1', 'ksvs1', 'ts1', 'ts2', 'ts3', 'ts4',
              'k2', 't3', 'ksvs2', 'ts5', 'ts6', 'ts7', 'ts8', 'vl', 'pl',
              'td', 'tsf', 't2', 'bmax', 'bmin', 'tsw', 'vemax',
              'vemin', 'kitg1', 'vimax', 'vimin', 'twp', 'pemax', 'pemin',
              'kitg2', 'pimax', 'pimin', 'qcomp', 'vcomp', 'pcomp',
              'tvcomp', 'tpcomp', 'vquit', 'pquit', 'tvquit', 'tpquit',
              'modeqt', 'qbquit', 'note'],
        sgen=['par_no', 'im', 'isc', 'vm', 'voc', 'smax', 'smin', 'kiv',
              'kv', 'tv', 'ki2', 'ki', 'ti', 'kpwm', 'tl', 'imax', 'imin',
              'kf', 'tc', 'amax', 'amin', 'site', 't', 'v1', 'v2', 'v3',
              'v4', 'tv1', 'tv2', 'tv3', 'tv4', 'tvback', 'f1', 'f2',
              'f3', 'f4', 'tf1', 'tf2', 'tf3', 'tf4', 'tfback', 'i1', 'i2',
              'ti1', 'ti2', 'ti3', 'tiback', 'v21', 'v22', 'te1', 'te2',
              'teback', 'tback', 'vtbase', 'isprct', 'note'],
        ds3=['par_no', 'tr1', 'kr', 'db1', 'k1', 't1', 'dfmax1', 'dfmin1',
             'intmax1', 'intmin1', 'pmax1', 'pmin1', 'tr2', 'ki', 'db2',
             'k2', 't2', 'dfmax2', 'dfmin2', 'intmax2', 'intmin2',
             'pmax2', 'pmin2', 'note'],
        gov8=['par_no', 't1', 'tr1', 'db1p', 'db1n', 'max1', 'min1',
              'rti1', 'rtd1', 'mode', 't2', 'tr2', 'ep', 'db2', 'max2',
              'min2', 'rti2', 'rtd2', 'kp1', 'ki1', 'kd1', 'td1',
              'intmax1', 'intmin1', 'pidmax1', 'pidmin1', 'nmc', 'npa',
              't3', 'tr3', 'bp', 'db3', 'max3', 'min3', 'kp2', 'ki2',
              'kd2', 'td2', 'intmax2', 'intmin2', 'pidmax2', 'pidmin2',
              'kw', 'wcp', 'wcn', 'dbip', 'dbin', 'tdy1', 'tdy2', 'maxi',
              'mini', 'kpi', 'kii', 'kdi', 'bpi', 'kp', 'kd', 'ki',
              'intmax', 'intmin', 'pidmax', 'pidmin', 'tc', 'topen', 'tf',
              'tdy', 'velc', 'velo', 'pmax', 'pmin', 'y1', 'q1', 'y2',
              'q2', 'y3', 'q3', 'a', 'b', 'tw', 'rti0', 'rtd0', 'dp1',
              'dp2', 'tqm', 'kp3', 'ki3', 'kd3', 'td3', 'dbhp', 't4',
              'note'],
        gov9=['par_no', 't1', 'death', 'k_rev', 'kmct', 'kp1', 'kd1',
              'ki1', 'imax1', 'imin1', 'pmax1', 'pmin1', 'k2', 'ffmax',
              'ffmin', 'tc', 'topen', 'velc', 'velo', 'pmax', 'pmin',
              'tf', 'kp', 'kd', 'ki', 'imax', 'imin', 'pidmax', 'pidmin',
              'tch', 'fhp', 'trh', 'fip', 'tco', 'flp', 'lnd', 'tsh',
              'td', 'tw', 'k_mp', 'tdly', 'vmax', 'vmin', 'tr_pm',
              'tr_pe', 'tdelay1', 'tdelay2', 'tdelay3', 'rr', 'rf',
              'note'],
        dc1=['par_no', 'g_amax', 't_amax', 'gammaref', 'gammamin',
             'kp_vca', 'ti_vca', 'k1_ra', 'k2_ra', 'cdl', 'dl', 'decr',
             't_ga', 'td_ret', 'th_ret', 'th_res', 'mode', 'lead',
             'fp_co', 'bc_on', 'udlow', 'udhigh', 'udtup', 'udtdn',
             'iomin_vdcl', 'iomin', 'id_t', 'gain', 'kp', 'ti', 'g_cf',
             'k_cf', 't_dn_cf', 'alpha_res', 'u_enable', 'uk',
             'gama_fail', 'iovs', 'tovs', 'iovl', 'tovl', 'tflock',
             'cfo_f', 'cfo_comdy', 'cfo_iomin', 'cfo_amax', 'cfo_srt',
             'cfo_vth', 'cfo_idt', 'cfo_rdt', 'cfo_dcb', 'note'],
        pss7=['par_no', 'la', 'lb', 'lc', 'ca', 'cb', 'cd', 'cf', 't1',
              'kl', 'kl1', 'kl2', 'kl3', 'kl4', 'tl1', 'tl2', 'tl3',
              'tl4', 'tl5', 'tl6', 'tl7', 'tl8', 'tl9', 'tl10', 'tl11',
              'tl12', 'vlmax', 'vlmin', 'ki', 'ki1', 'ki2', 'ki3', 'ki4',
              'ti1', 'ti2', 'ti3', 'ti4', 'ti5', 'ti6', 'ti7', 'ti8',
              'ti9', 'ti10', 'ti11', 'ti12', 'vimax', 'vimin', 'kh',
              'kh1', 'kh2', 'kh3', 'kh4', 'th1', 'th2', 'th3', 'th4',
              'th5', 'th6', 'th7', 'th8', 'th9', 'th10', 'th11',
              'th12', 'vhmax', 'vhmin', 'vsmax', 'vsmin', 'note'],
        vsc=['par_no', 'flag', 'mode', 'cp', 'kp_p', 'ti_p', 'kp_q',
             'ti_q', 'kp_ud', 'ti_ud', 'max_p', 'min_p', 'max_q', 'min_q',
             'max_ud', 'min_ud', 'kp_udlim', 'ti_udlim', 'udref_max',
             'udref_min', 'max_udlim', 'min_udlim', 'kp_id', 'ti_id',
             'kp_iq', 'ti_iq', 'max_id', 'min_id', 'max_iq', 'min_iq',
             'note'],
        gov10=['par_no', 't1', 'tr1', 'kw', 'db1p', 'db1n', 'dmax1',
               'dmin1', 'kp', 'ki', 'kd', 'tv', 'imax', 'imin', 'pidmax',
               'pidmin', 'mode', 'pflag', 'bpflag', 't2', 'tr2',
               'digisamp', 'ep', 'rr', 'rf', 'db2p', 'db2n', 'dbmax2',
               'dbmin2', 't3', 'tr3', 'p1', 'p2', 'p3', 'kp21', 'ki21',
               'kd21', 'td21', 'kp22', 'ki22', 'kd22', 'td22', 'kp23',
               'ki23', 'kd23', 'td23', 'imax2', 'imin2', 'pidmax2',
               'pidmin2', 'fh', 'fl', 'tdelay', 'tmode', 'kps', 'kis',
               'kds', 'imaxs', 'imins', 'pidmaxs', 'pidmins', 'tos',
               'tcs', 'velclose', 'velopen', 'dbsp', 'dbsn', 'psmax',
               'psmin', 't2s', 't3s', 't4s', 'yy1', 'q1', 'yy2', 'q2',
               'yy3', 'q3', 'kp1', 'kp2', 'kr', 'a', 'b', 'tw', 'kpj',
               'kij', 'kdj', 'imaxj', 'iminj', 'pidmaxj', 'pidminj',
               'toj', 'tcj', 'velclosej', 'velopenj', 'dbjp', 'dbjn',
               'pjmax', 'pjmin', 't2j', 't3j', 't4j', 'x1', 'y1', 'x2',
               'y2', 'x3', 'y3', 'x4', 'y4', 'x5', 'y5', 'x6', 'y6', 'x7',
               'y7', 'x8', 'y8', 'x9', 'y9', 'x10', 'y10', 'bp',
               'nsource', 'note'],
        avr16=['par_no', 'tr', 'kc1', 'kc2', 'vrmax', 'vrmin', 'k', 'kv',
               't1', 't2', 't3', 't4', 'ka', 'ta', 'vmax', 'vmin', 'vamax',
               'vamin', 'kf', 'tf', 'lkp', 'lkn', 'hlction', 'kh', 'th1',
               'th2', 'ifmax', 'ifc', 'ifl', 'b', 'kfh', 'lction', 'swl',
               'tl1', 'tl2', 'tl3', 'tl4', 'tlu', 'kl', 'klv', 'vuelmax',
               'vuelmin', 'pl1', 'ql1', 'pl2', 'ql2', 'pl3', 'ql3', 'pl4',
               'ql4', 'pl5', 'ql5', 'dlction', 'td1', 'td2', 'kd', 'itl',
               'itc', 'bd', 'kth', 'tq1', 'tq2', 'tq3', 'tq4', 'tu', 'kq',
               'kqv', 'tdy', 'tsf', 'voelmax', 'voelmin', 'ph1', 'qh1',
               'ph2', 'qh2', 'ph3', 'qh3', 'ph4', 'qh4', 'ph5', 'qh5',
               'note'],
        le1=['par_no', 'tr', 'pmax', 'pmin', 'p1', 'q1', 'p2', 'q2',
             'p3', 'q3', 'p4', 'q4', 'p5', 'q5', 'p6', 'q6', 'p7', 'q7',
             'uth', 'uat', 'tqa', 'dqr', 'kq', 't1', 't2', 'qcmax',
             'qcmin', 'qd', 'tqd', 'note'],
        vsc2=['par_no', 'cway', 'ctype', 'tr', 'k1', 'ki1', 'k2', 'ki2',
              'idmax', 'idmin', 'iqmax', 'iqmin', 'idomax', 'idomin',
              'iqomax', 'iqomin', 'dctype', 'altn', 'kpd1', 'kid1',
              'kpd2', 'kid2', 'kpd3', 'kid3', 'kdd1', 'tdd1', 'kdd2',
              'tdd2', 'kdd3', 'tdd3', 'id1max', 'id1min', 'ido1max',
              'ido1min', 'id2max', 'id2min', 'ido2max', 'ido2min',
              'id3max', 'id3min', 'ido3max', 'ido3min', 'udcrefl',
              'udcrefh', 'ku', 'kp', 'qctype', 'kpq', 'kiq', 'iq1max',
              'iq1min', 'kdq', 'tdq', 'iqo1max', 'iqo1min', 'isolt',
              'ratphaf', 'pll_kp', 'negnk', 'ak2pd', 'ak2id', 'a2mxid',
              'a2mnid', 'a2mxd', 'a2mnd', 'ak2pq', 'ak21q', 'a2mxiq',
              'a2mniq', 'a2mxq', 'a2mnq', 'a2limit', 'vach', 'vacl',
              'vdch1', 'vdcl1', 'pcovup', 'tpcov', 'aup1', 'tacbk',
              'cbreak', 'tracd', 'trdcd', 'pll_ki', 'eacd', 'edcd',
              'eacq', 'vcacup', 'vcaclw', 'vconup', 'vconlw', 'vbacup',
              'vbaclw', 'distrqd', 'vacprup', 'vacprlw', 'vacbcup',
              'vacbclw', 'frqprup', 'frqprlw', 'frqbcup', 'frqbclw',
              'kpq2', 'kiq2', 'iq2max', 'iq2min', 'kdq2', 'tdq2',
              'iqo2max', 'iqo2min', 'dcstep', 'taup1', 'hmratio',
              'hmdecra', 'tvach', 'tvacl', 'vdch2', 'vdcl2', 'tvdch1',
              'tvdcl1', 'tvdch2', 'tvdcl2', 'aup2', 'taup2', 'aup3',
              'taup3', 'aupgr', 'taupgr', 'vunb1', 'vunb2', 'tvunb1',
              'tvunb2', 'aunb1', 'aunb2', 'taunb1', 'taunb2', 'trescon',
              'timres', 'tresacc', 'tresval', 'trescre', 'fcovup',
              'tfcovup', 'fcovlw', 'tfcovlw', 'tvcacup', 'tvcaclw',
              'alimcd1', 'kidw', 'alimcd2', 'ua1', 'ua2', 'kiup',
              'puprat', 'plwrat', 'uduprat', 'udlwrat', 'rcharg',
              'rdiode', 'quprat', 'qlwrat', 'uauprat', 'ualwrat',
              'duacrefl', 'duacrefh', 'pzz1', 'pzz2', 'pzz3', 'pzz4',
              'pzz5', 'pzz6', 'pzz7', 'pzz8', 'pzz9', 'quu1', 'quu2',
              'quu3', 'quu4', 'quu5', 'quu6', 'quu7', 'quu8', 'quu9',
              'qww1', 'qww2', 'qww3', 'qww4', 'qww5', 'qww6', 'qww7',
              'qww8', 'qww9', 'alimcq1', 'tua1', 'tpex1', 'tqex1',
              'tvex1', 'ub1', 'uc1', 'ud1', 'tuc1', 'coupv', 'ub2',
              'tua2', 'alimcq2', 'uc2', 'tuc2', 'tdcvex1', 'coupp',
              'forwp', 'satup', 'forwdcv', 'satudcv', 'forwq', 'satuq',
              'follwq', 'satuacv', 'satuf', 'vupin', 'vlowin', 'kiupq',
              'tuefsmo', 'ue1', 'uf1', 'tue1', 'tuf1', 'tub1', 'tud1',
              'tub2', 'tud2', 'ud2', 'tpex2', 'tqex2', 'tvex2', 'tdcvex2',
              'alimfd1', 'alimfq1', 'alimfd2', 'alimfq2', 'ifaucd1',
              'ifaucq1', 'ifaucd2', 'ifaucq2', 'ifaufd1', 'ifaufq1',
              'ifaufd2', 'ifaufq2', 'ifausd1', 'ifausq1', 'ifausd2',
              'ifausq2', 'iforb', 'r_acp', 'x_acp', 'grp_acp', 'vin_acp',
              'tin_acp', 'vout_acp', 'tout_acp', 'rt_acp', 'xt_acp',
              'ton_acp', 'toff_acp', 'contyp', 'alim1', 'alim2', 'darfd1',
              'darfq1', 'daefd2', 'daefq2', 'kupd0', 'fordplim',
              'tbefupd', 'tlimfordp', 'abslowa', 'unlimq1', 'unlimq2',
              'chgvactr', 'kpq3', 'kiq3', 'iqo3max', 'iqo3min', 'oppstr',
              'vchgrat', 'kiupdx', 'kiupqx', 'kdcsca', 'vmodup',
              'vmodlw', 'tmody', 'freqmd', 'tfreq', 'di1', 'akp1', 'di2',
              'akp2', 'pco_kp', 'lockun', 'fconv', 'fcont', 'akvup0',
              'akvup', 'linlimun', 'uaclim1', 'aclim1', 'uaclim2',
              'aclim2', 'uaclim3', 'aclim3', 'uaclim4', 'aclim4',
              'uaclim5', 'aclim5', 'aciup', 'udcoup', 'udcolw', 'tudco',
              'udcomg', 'incrdu', 'decrdu', 'iconqv', 'udcinup',
              'udcinlw', 'back44', 'back45', 'back46', 'note'],
        mdcln1=['par_no', 'vpdcup', 'vpdclw', 'apdcup', 'tpdcup',
                'apdcdf', 'tdcbrk', 'idcbk', 'tpdcdf', 'tpdvah', 'tpdval',
                'vvlih', 'avlih', 'tvlih1', 'tvlih2', 'trest', 'tretval',
                'timres', 'lkvsc', 'tmsi', 'nifilt1', 'chi1', 'lmi1',
                'rmi1', 'cli1', 'lli1', 'rli1', 'nifilt2', 'chi2', 'lmi2',
                'rmi2', 'cli2', 'lli2', 'rli2', 'njfilt1', 'chj1', 'lmj1',
                'rmj1', 'clj1', 'llj1', 'rlj1', 'njfilt2', 'chj2', 'lmj2',
                'rmj2', 'clj2', 'llj2', 'rlj2', 'ci0', 'cj0', 'sdio',
                'rdio', 'adio', 'udio', 'sthy', 'rthy', 'uthy1', 'uthy2',
                'note'],
        oe1=['par_no', 'kl1', 'ifdlim', 'ifdinf', 'b', 'c', 't', 'kl2',
             'tl1', 'tl2', 'valid1', 'valid2', 'note'],
        le2=['par_no', 'ntype', 'kh', 't1', 't2', 'p1', 'q1', 'p2',
             'q2', 'p3', 'q3', 'p4', 'q4', 'p5', 'q5', 'note'],
        ds4=['par_no', 'tr', 'kr', 'dfrmax', 'dfrmin', 'drplus',
             'drminus', 'tr1', 'tr2', 'tr3', 'tr4', 'tr5', 'kr1',
             'ti', 'ki', 'dfimax', 'dfimin', 'diplus', 'diminus', 'ti1',
             'ti2', 'ti3', 'ti4', 'ti5', 'ki1', 'pmodmax', 'pmodmin',
             'note'],
        pss8=['par_no', 'kqv', 'tqv', 'tq1', 'tq1p', 'tq2', 'tq2p',
              'tq3', 'tq3p', 'vsmax', 'vsmin', 'note'],
        pmac=['par_no', 'tr', 't1', 't2', 'kh', 'kq', 'kv', 'ti', 'utl',
              'uth', 'uhl', 'uhh', 'note'],
        dfig2=['par_no', 'wtgmodel', 'gratepower', 'omega_base',
               'tj_gen', 'rs', 'rr', 'ls', 'lr', 'lm', 'td0p', 'lss',
               'lrr', 'lp', 'a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7',
               'a8', 'a9', 'a10', 'a11', 'a12', 'a13', 'a14', 'a15', 'a16',
               'a17', 'a18', 'a19', 'a20', 'a21', 'a22', 'a23', 'a24',
               'a25', 'vwind_rate', 'vwind0', 'vwind_ci', 'vwind_co',
               'rho', 'kb', 'rhoar2', 'nwfflg', 'turbine_radius',
               'omega_base_t', 'tj_turbine', 'omega_rate',
               'omega_base_t_conv', 'omega_base_conv', 'gratepower_conv',
               'nturbine_model', 'axis_flex', 'axis_damp', 'dpord_max',
               'dpord_min', 'temax', 'temin', 'dtemax', 'dtemin', 'twgen',
               'twref', 'woffset', 'kptrq', 'kitrq', 'speedpeflag', 'p1',
               'spd1', 'p2', 'spd2', 'p3', 'spd3', 'p4', 'spd4', 'kpw',
               'kiw', 'kpc', 'kic', 'kcc', 'ttheta', 'thetamax',
               'thetamin', 'dthetamax', 'dthetamin', 'nwdinflg', 'kwi',
               'dbwi', 'tlpwi', 'twowi', 'urlwi', 'drlwi', 'pmxwi',
               'pmnwi', 'kptrq_aft_wndint', 'kitrq_aft_wndint',
               'tpord_aft_wndint', 'ndbrflg', 'ebst', 'kdbr', 'vlin',
               'vlout', 'vhin', 'vhout', 'vl1', 'vl2', 'tl1', 'tl2',
               'vh1', 'vh2', 'th1', 'th2', 'nlvrtflg', 'lvrtportion',
               'hvrtportion', 'tdlyvlin', 'tdlyvlout', 'tdlyvhin',
               'tdlyvhout', 'pq_flag', 'pq_lhvrt_flag',
               'ipcll_lhvrt_norm_flag', 'vq1', 'iq1', 'vq2', 'iq2', 'vq3',
               'iq3', 'vq4', 'iq4', 'vp1', 'ip1', 'vp2', 'ip2', 'vp3',
               'ip3', 'vp4', 'ip4', 'tfltr', 'trp', 'trf', 'trv',
               'freq_flag', 'krp', 'ppoi_flag', 'fdb1', 'fdb2', 'dup',
               'ddn', 'dup_pmax', 'ddn_pmin', 'perrmax', 'perrmin',
               'kp_pp', 'ki_pp', 'ppoimax', 'ppoimin', 'tlag',
               'vcmp_flag', 'pfpoi_flag', 'qpoi_flag', 'rc',
               'xc', 'kc', 'vpdb1', 'vpdb2', 'verrmax', 'verrmin',
               'kp_pv', 'ki_pv', 'qpdb1', 'qpdb2', 'qerrmax', 'qerrmin',
               'kp_pq', 'ki_pq', 'qpoimax', 'qpoimin', 'tft', 'tfv',
               'pmax', 'pmin', 'qmax', 'qmin', 'dpmax', 'dpmin', 'dqmax',
               'dqmin', 'ip_max', 'ip_min', 'iq_max', 'iq_min', 'i_max',
               'i_min', 'tg', 'p_flag', 'tpord', 'kp_lp', 'ki_lp', 'tip',
               'qref_flag', 'v_flag', 'q_flag', 'tqord', 'tiq', 'kp_lqv',
               'ki_lqv', 'v_max', 'v_min', 'kp_lv', 'ki_lv', 'kp_lq',
               'ki_lq', 'vldb1', 'vldb2', 'kqv', 'iqinjh', 'iqinjl',
               'lvrt_in_pflag', 'kp_lvrt', 'pset_lv', 'k1_ip_lv',
               'k2_ip_lv', 'ipset_lv', 'vzerox', 'vbrkpt', 'ipbrkpt',
               'lvrt_in_qflag', 'kq_lv', 'qset_lv', 'k1_iq_lv',
               'k2_iq_lv', 'iqset_lv', 'ip_lvrec0_flag', 'kip_lvrec0',
               'ipset_lvrec0', 'tlvrt_recover0', 'iq_lvrec0_flag',
               'kiq_lvrec0', 'iqset_lvrec0', 'hvrt_in_pflag', 'kp_hv',
               'pset_hv', 'k1_ip_hv', 'k2_ip_hv', 'ipset_hv',
               'hvrt_in_qflag', 'kq_hv', 'qset_hv', 'k1_iq_hv',
               'k2_iq_hv', 'iqset_hv', 'ip_hvrec0_flag', 'kip_hvrec0',
               'ipset_hvrec0', 'thvrt_recover0', 'iq_hvrec0_flag',
               'kiq_hvrec0', 'iqset_hvrec0', 'lvrt_recover_pflag',
               'dip_recover_max', 'tcons_precover', 'ip_rec_a',
               'ip_rec_b', 'ip_rec_c', 'ip_rec_d', 'ip_rec_t0',
               'lvrt_recover_qflag', 'tcons_qrecover', 'icontyp_ubl',
               'ik1_ip_lv_ubl', 'ik2_ip_lv_ubl', 'iipset_lv_ubl',
               'ik3_ip_lv_ubl', 'ik1_iq_lv_ubl', 'ik2_iq_lv_ubl',
               'iiqset_lv_ubl', 'ik3_iq_lv_ubl', 'lvrt_flag',
               'hvlt_flag', 'temp1', 'temp2', 'temp3', 'temp4', 'temp5',
               'temp6', 'temp7', 'temp8', 'temp9', 'temp10', 'note'],
        pmsg2=['par_no', 'wtgmodel', 'gratepower', 'omega_base',
               'tj_gen', 'rs', 'rr', 'ls', 'lr', 'lm', 'td0p', 'lss',
               'lrr', 'lp', 'a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7',
               'a8', 'a9', 'a10', 'a11', 'a12', 'a13', 'a14', 'a15',
               'a16', 'a17', 'a18', 'a19', 'a20', 'a21', 'a22', 'a23',
               'a24', 'a25', 'vwind_rate', 'vwind0', 'vwind_ci',
               'vwind_co', 'rho', 'kb', 'rhoar2', 'nwfflg',
               'turbine_radius', 'omega_base_t', 'tj_turbine',
               'omega_rate', 'omega_base_t_conv', 'omega_base_conv',
               'gratepower_conv', 'nturbine_model', 'axis_flex',
               'axis_damp', 'dpord_max', 'dpord_min', 'temax', 'temin',
               'dtemax', 'dtemin', 'twgen', 'twref', 'woffset', 'kptrq',
               'kitrq', 'speedpeflag', 'p1', 'spd1', 'p2', 'spd2', 'p3',
               'spd3', 'p4', 'spd4', 'kpw', 'kiw', 'kpc', 'kic', 'kcc',
               'ttheta', 'thetamax', 'thetamin', 'dthetamax', 'dthetamin',
               'nwdinflg', 'kwi', 'dbwi', 'tlpwi', 'twowi', 'urlwi',
               'drlwi', 'pmxwi', 'pmnwi', 'kptrq_aft_wndint',
               'kitrq_aft_wndint', 'tpord_aft_wndint', 'ndbrflg',
               'ebst', 'kdbr', 'vlin', 'vlout', 'vhin', 'vhout', 'vl1',
               'vl2', 'tl1', 'tl2', 'vh1', 'vh2', 'th1', 'th2',
               'nlvrtflg', 'lvrtportion', 'hvrtportion', 'tdlyvlin',
               'tdlyvlout', 'tdlyvhin', 'tdlyvhout', 'pq_flag',
               'pq_lhvrt_flag', 'ipcll_lhvrt_norm_flag', 'vq1', 'iq1',
               'vq2', 'iq2', 'vq3', 'iq3', 'vq4', 'iq4', 'vp1', 'ip1',
               'vp2', 'ip2', 'vp3', 'ip3', 'vp4', 'ip4', 'tfltr', 'trp',
               'trf', 'trv', 'freq_flag', 'krp', 'ppoi_flag', 'fdb1',
               'fdb2', 'dup', 'ddn', 'dup_pmax', 'ddn_pmin', 'perrmax',
               'perrmin', 'kp_pp', 'ki_pp', 'ppoimax', 'ppoimin',
               'tlag', 'vcmp_flag', 'pfpoi_flag', 'qpoi_flag', 'rc',
               'xc', 'kc', 'vpdb1', 'vpdb2', 'verrmax', 'verrmin',
               'kp_pv', 'ki_pv', 'qpdb1', 'qpdb2', 'qerrmax', 'qerrmin',
               'kp_pq', 'ki_pq', 'qpoimax', 'qpoimin', 'tft', 'tfv',
               'pmax', 'pmin', 'qmax', 'qmin', 'dpmax', 'dpmin', 'dqmax',
               'dqmin', 'ip_max', 'ip_min', 'iq_max', 'iq_min', 'i_max',
               'i_min', 'tg', 'p_flag', 'tpord', 'kp_lp', 'ki_lp', 'tip',
               'qref_flag', 'v_flag', 'q_flag', 'tqord', 'tiq',
               'kp_lqv', 'ki_lqv', 'v_max', 'v_min', 'kp_lv', 'ki_lv',
               'kp_lq', 'ki_lq', 'vldb1', 'vldb2', 'kqv', 'iqinjh',
               'iqinjl', 'lvrt_in_pflag', 'kp_lvrt', 'pset_lv',
               'k1_ip_lv', 'k2_ip_lv', 'ipset_lv', 'vzerox', 'vbrkpt',
               'ipbrkpt', 'lvrt_in_qflag', 'kq_lv', 'qset_lv',
               'k1_iq_lv', 'k2_iq_lv', 'iqset_lv', 'ip_lvrec0_flag',
               'kip_lvrec0', 'ipset_lvrec0', 'tlvrt_recover0',
               'iq_lvrec0_flag', 'kiq_lvrec0', 'iqset_lvrec0',
               'hvrt_in_pflag', 'kp_hv', 'pset_hv', 'k1_ip_hv',
               'k2_ip_hv', 'ipset_hv', 'hvrt_in_qflag', 'kq_hv',
               'qset_hv', 'k1_iq_hv', 'k2_iq_hv', 'iqset_hv',
               'ip_hvrec0_flag', 'kip_hvrec0', 'ipset_hvrec0',
               'thvrt_recover0', 'iq_hvrec0_flag', 'kiq_hvrec0',
               'iqset_hvrec0', 'lvrt_recover_pflag', 'dip_recover_max',
               'tcons_precover', 'ip_rec_a', 'ip_rec_b', 'ip_rec_c',
               'ip_rec_d', 'ip_rec_t0', 'lvrt_recover_qflag',
               'tcons_qrecover', 'icontyp_ubl', 'ik1_ip_lv_ubl',
               'ik2_ip_lv_ubl', 'iipset_lv_ubl', 'ik3_ip_lv_ubl',
               'ik1_iq_lv_ubl', 'ik2_iq_lv_ubl', 'iiqset_lv_ubl',
               'ik3_iq_lv_ubl', 'lvrt_flag', 'hvlt_flag', 'temp1',
               'temp2', 'temp3', 'temp4', 'temp5', 'temp6', 'temp7',
               'temp8', 'temp9', 'temp10', 'note'],
        pv2=['par_no', 'weccmodel', 'gratepower', 'sref', 'b_battery',
             'soc_max', 'soc_min', 'soc_ini', 't_total', 'vlin', 'vlout',
             'vhin', 'vhout', 'vl1', 'vl2', 'tl1', 'tl2', 'vh1', 'vh2',
             'th1', 'th2', 'nlvrtflg', 'lvrtportion', 'hvrtportion',
             'tdlyvlin', 'tdlyvlout', 'tdlyvhin', 'tdlyvhout', 'pq_flag',
             'pq_lhvrt_flag', 'ipcll_lhvrt_norm_flag', 'vq1', 'iq1',
             'vq2', 'iq2', 'vq3', 'iq3', 'vq4', 'iq4', 'vp1', 'ip1',
             'vp2', 'ip2', 'vp3', 'ip3', 'vp4', 'ip4', 'tfltr', 'trp',
             'trf', 'trv', 'freq_flag', 'krp', 'ppoi_flag', 'fdb1',
             'fdb2', 'dup', 'ddn', 'dup_pmax', 'ddn_pmin', 'perrmax',
             'perrmin', 'kp_pp', 'ki_pp', 'ppoimax', 'ppoimin', 'tlag',
             'vcmp_flag', 'pfpoi_flag', 'qpoi_flag', 'rc', 'xc', 'kc',
             'vpdb1', 'vpdb2', 'verrmax', 'verrmin', 'kp_pv', 'ki_pv',
             'qpdb1', 'qpdb2', 'qerrmax', 'qerrmin', 'kp_pq', 'ki_pq',
             'qpoimax', 'qpoimin', 'tft', 'tfv', 'pmax', 'pmin', 'qmax',
             'qmin', 'dpmax', 'dpmin', 'dqmax', 'dqmin', 'ip_max',
             'ip_min', 'iq_max', 'iq_min', 'i_max', 'i_min', 'tg',
             'p_flag', 'tpord', 'kp_lp', 'ki_lp', 'tip', 'qref_flag',
             'v_flag', 'q_flag', 'tqord', 'tiq', 'kp_lqv', 'ki_lqv',
             'v_max', 'v_min', 'kp_lv', 'ki_lv', 'kp_lq', 'ki_lq',
             'vldb1', 'vldb2', 'kqv', 'iqinjh', 'iqinjl', 'lvrt_in_pflag',
             'kp_lvrt', 'pset_lv', 'k1_ip_lv', 'k2_ip_lv', 'ipset_lv',
             'vzerox', 'vbrkpt', 'ipbrkpt', 'lvrt_in_qflag', 'kq_lv',
             'qset_lv', 'k1_iq_lv', 'k2_iq_lv', 'iqset_lv',
             'ip_lvrec0_flag', 'kip_lvrec0', 'ipset_lvrec0',
             'tlvrt_recover0', 'iq_lvrec0_flag', 'kiq_lvrec0',
             'iqset_lvrec0', 'hvrt_in_pflag', 'kp_hv', 'pset_hv',
             'k1_ip_hv', 'k2_ip_hv', 'ipset_hv', 'hvrt_in_qflag',
             'kq_hv', 'qset_hv', 'k1_iq_hv', 'k2_iq_hv', 'iqset_hv',
             'ip_hvrec0_flag', 'kip_hvrec0', 'ipset_hvrec0',
             'thvrt_recover0', 'iq_hvrec0_flag', 'kiq_hvrec0',
             'iqset_hvrec0', 'lvrt_recover_pflag', 'dip_recover_max',
             'tcons_precover', 'ip_rec_a', 'ip_rec_b', 'ip_rec_c',
             'ip_rec_d', 'ip_rec_t0', 'lvrt_recover_qflag',
             'tcons_qrecover', 'icontyp_ubl', 'ik1_ip_lv_ubl',
             'ik2_ip_lv_ubl', 'iipset_lv_ubl', 'ik3_ip_lv_ubl',
             'ik1_iq_lv_ubl', 'ik2_iq_lv_ubl', 'iiqset_lv_ubl',
             'ik3_iq_lv_ubl', 'lvrt_flag', 'hvlt_flag', 'temp1',
             'temp2', 'temp3', 'temp4', 'temp5', 'temp6', 'temp7',
             'temp8', 'temp9', 'temp10', 'note'],
        bess=['par_no', 'weccmodel', 'gratepower', 'sref', 'b_battery',
              'soc_max', 'soc_min', 'soc_ini', 't_total', 'vlin', 'vlout',
              'vhin', 'vhout', 'vl1', 'vl2', 'tl1', 'tl2', 'vh1', 'vh2',
              'th1', 'th2', 'nlvrtflg', 'lvrtportion', 'hvrtportion',
              'tdlyvlin', 'tdlyvlout', 'tdlyvhin', 'tdlyvhout', 'pq_flag',
              'pq_lhvrt_flag', 'ipcll_lhvrt_norm_flag', 'vq1', 'iq1',
              'vq2', 'iq2', 'vq3', 'iq3', 'vq4', 'iq4', 'vp1', 'ip1',
              'vp2', 'ip2', 'vp3', 'ip3', 'vp4', 'ip4', 'tfltr', 'trp',
              'trf', 'trv', 'freq_flag', 'krp', 'ppoi_flag', 'fdb1',
              'fdb2', 'dup', 'ddn', 'dup_pmax', 'ddn_pmin', 'perrmax',
              'perrmin', 'kp_pp', 'ki_pp', 'ppoimax', 'ppoimin', 'tlag',
              'vcmp_flag', 'pfpoi_flag', 'qpoi_flag', 'rc', 'xc', 'kc',
              'vpdb1', 'vpdb2', 'verrmax', 'verrmin', 'kp_pv', 'ki_pv',
              'qpdb1', 'qpdb2', 'qerrmax', 'qerrmin', 'kp_pq', 'ki_pq',
              'qpoimax', 'qpoimin', 'tft', 'tfv', 'pmax', 'pmin', 'qmax',
              'qmin', 'dpmax', 'dpmin', 'dqmax', 'dqmin', 'ip_max',
              'ip_min', 'iq_max', 'iq_min', 'i_max', 'i_min', 'tg',
              'p_flag', 'tpord', 'kp_lp', 'ki_lp', 'tip', 'qref_flag',
              'v_flag', 'q_flag', 'tqord', 'tiq', 'kp_lqv', 'ki_lqv',
              'v_max', 'v_min', 'kp_lv', 'ki_lv', 'kp_lq', 'ki_lq',
              'vldb1', 'vldb2', 'kqv', 'iqinjh', 'iqinjl',
              'lvrt_in_pflag', 'kp_lvrt', 'pset_lv', 'k1_ip_lv',
              'k2_ip_lv', 'ipset_lv', 'vzerox', 'vbrkpt', 'ipbrkpt',
              'lvrt_in_qflag', 'kq_lv', 'qset_lv', 'k1_iq_lv',
              'k2_iq_lv', 'iqset_lv', 'ip_lvrec0_flag', 'kip_lvrec0',
              'ipset_lvrec0', 'tlvrt_recover0', 'iq_lvrec0_flag',
              'kiq_lvrec0', 'iqset_lvrec0', 'hvrt_in_pflag', 'kp_hv',
              'pset_hv', 'k1_ip_hv', 'k2_ip_hv', 'ipset_hv',
              'hvrt_in_qflag', 'kq_hv', 'qset_hv', 'k1_iq_hv',
              'k2_iq_hv', 'iqset_hv', 'ip_hvrec0_flag', 'kip_hvrec0',
              'ipset_hvrec0', 'thvrt_recover0', 'iq_hvrec0_flag',
              'kiq_hvrec0', 'iqset_hvrec0', 'lvrt_recover_pflag',
              'dip_recover_max', 'tcons_precover', 'ip_rec_a',
              'ip_rec_b', 'ip_rec_c', 'ip_rec_d', 'ip_rec_t0',
              'lvrt_recover_qflag', 'tcons_qrecover', 'icontyp_ubl',
              'ik1_ip_lv_ubl', 'ik2_ip_lv_ubl', 'iipset_lv_ubl',
              'ik3_ip_lv_ubl', 'ik1_iq_lv_ubl', 'ik2_iq_lv_ubl',
              'iiqset_lv_ubl', 'ik3_iq_lv_ubl', 'lvrt_flag', 'hvlt_flag',
              'temp1', 'temp2', 'temp3', 'temp4', 'temp5', 'temp6',
              'temp7', 'temp8', 'temp9', 'temp10', 'note'],
        upfc_ps=['par_no', 'tv', 'kiv', 'vdimax', 'vdimin', 'kpv',
                 'ipqmax', 'ipqmin', 'tish', 'thsh', 'tdv', 'kidv',
                 'vdcmax', 'vdcmin', 'kpdv', 'overvoltage', 'ovtime',
                 'undervoltage', 'uvtime', 'overfrequency', 'oftime',
                 'underfrequency', 'uftime', 'overcurrent', 'octime',
                 'odcv', 'odcvtime', 'note'],
        upfc_ss=['par_no', 'tp', 'kip', 'pdimax', 'pdimin', 'kpp', 'tq',
                 'kiq', 'qdimax', 'qdimin', 'kpq', 'vpqmax', 'vpqmin',
                 'tvpq', 'thpq', 'overcurrent', 'octime', 'note'],
        lcc6=['par_no', 'dtlcc', 'rthyr', 'vthyopn', 'vthyclo',
              'deg_fail', 'crc', 'rrc', 'pll_kp', 'pll_ki', 'pco_kp',
              'tracv', 'trdcv', 'trdci', 'ibc_on', 'icmunit', 'tcmunit',
              'raovs', 'tovs', 'raovl', 'tovl', 'numovs', 'tlimovs',
              'puprat', 'plwrat', 'vshif_ir', 'tvdcs_ir', 'tvdcf_ir',
              'tftos_ir', 'tstof_ir', 'vftlm_ir', 'compk_ir', 'compu_ir',
              'ud_low', 'ud_high', 't_ud_up', 't_ud_dn', 'iomin_vdcl',
              'io_min', 'icontyp', 'ts_cf_in', 'g_cf_a', 'uk_cf_abc',
              'uk_cf_s', 'a_cf_max1', 'a_cf_min1', 't_cf_hd1', 't_cf_hd2',
              't_cf_pls', 't_cf_on', 't_cf_off', 'uacs_acf', 'tuacs_acf',
              'tuach_acf', 'uacb_acf', 'tuacb_acf', 'tuaco_acf',
              'tuaca_acf', 'udcs_gm0', 'tudcs_gm0', 'tudch_gm0',
              'udcb_gm0', 'tudcb_gm0', 'igamatyp', 'a_comp', 'rf_t',
              'di_k', 'di_t', 'adimax', 'adimin', 'amaxup', 'amaxlw',
              'alpha_sub', 'alphalow', 't_slow', 'u1_ra', 'u2_ra',
              'raml1', 'raml2', 'decr', 't1s_ra', 't2s_ra', 't1b_ra',
              't2b_ra', 't1o_ra', 't2o_ra', 'du1_ra', 'tfilt_u',
              'udcuplim', 'udcdwlim', 'uov_ref', 'uov_tin', 'uov_tou',
              'uov_di', 'uov_kp', 'uov_ki', 'vca_kp', 'vca_ki',
              'vca_kp_up', 'vca_kp_lw', 'vca_mgn1', 'vca_mgn2',
              'vca_mgn3', 'alphe_ret', 'th_ret1', 'th_ret2', 'th_ret3',
              'alphe_res', 'th_res1', 'th_res2', 'th_res3', 'th_ress',
              'th_ressuc', 'th_lvpro', 'nful_res', 'ndep_res', 'udep_res',
              'vk_ressuc', 'vuprt_res', 'auprt_res', 'alim_lowv', 'diord',
              'tfilt_i', 'gaini', 'cca_kp', 'cca_ki', 'cca_kp_up',
              'cca_kp_lw', 'ain1', 'ain2', 'ain3', 'ain4', 'ain5',
              'ain6', 'aout1', 'aout2', 'aout3', 'aout4', 'aout5',
              'aout6', 'gca_kp', 'gca_ki', 'th_otc', 'ta_otc', 'dah_otc',
              'dal_otc', 'dvh_otc', 'dvl_otc', 'deh_otc', 'del_otc',
              'bra_th', 'bra_mx', 'bra_kp', 'bra_ki', 'bra_up', 'bra_lw',
              'nctrvorg', 't_addgm', 't_subgm', 'add_a_r_rat1',
              'add_a_r_lim1', 'add_a_r_1', 'sub_a_r_lim1',
              'sub_a_r_lim2', 'sub_a_r_rat1', 'sub_a_r_rat2',
              'sub_a_r_1', 'sub_a_r_2', 'sub_a_r_3', 'add_a_i_lim1',
              'add_a_i_lim2', 'add_a_i_lim3', 'add_a_i_1', 'add_a_i_2',
              'sub_a_i_lim1', 'emg_const', 'emg_volt', 'ange_lock',
              'tdy_lock', 'tsg_failu', 'tct_failu', 'ord_lock', 'temp1',
              'temp2', 'temp3', 'temp4', 'temp5', 'temp6', 'temp7',
              'temp8', 'temp9', 'temp10', 'temp11', 'temp12', 'temp13',
              'temp14', 'temp15', 'temp16', 'temp17', 'temp18', 'note'],
        svc5=['par_no', 'gratepower', 'trv', 'tri', 'trq', 'vdb1', 'vdb2',
              'tsr', 'vdv', 'ksl', 'ki_vr', 'kp_vr', 'dbmax_ki',
              'dbmin_ki', 'bmax', 'bmin', 'tsvc', 'flag_block',
              'vl_block', 'tdly_lv_block', 'vh_block', 'tdly_hv_block',
              'flag_uv', 'vl_uv', 'tdly_lv_uv', 'vh_uv', 'tdly_hv_uv',
              'qcomp_uv', 'flag_ov', 'vh_ov', 'tdly_hv_ov', 'vl_ov',
              'tdly_lv_ov', 'qcomp_ov', 'iflag_pod_p', 'tpod_p', 'tpw1',
              'tpw2', 'tps1', 'tps2', 'tps3', 'tps4', 'kpod_p',
              'iflag_pod_ib', 'tpod_ib', 'tibw1', 'tibw2', 'tibs1',
              'tibs2', 'tibs3', 'tibs4', 'kpod_ib', 'iflag_pod_dv',
              'tpod_dv', 'tdvw1', 'tdvw2', 'tdvs1', 'tdvs2', 'tdvs3',
              'tdvs4', 'kpod_dv', 'iflag_pod_f', 'tpod_f', 'tfw1', 'tfw2',
              'tfs1', 'tfs2', 'tfs3', 'tfs4', 'kpod_f', 'bpod_max',
              'bpod_min', 'temp1', 'temp2', 'temp3', 'temp4', 'temp5',
              'temp6', 'temp7', 'temp8', 'temp9', 'temp10', 'note'],
        lfod_vsc=['par_no', 'sitein', 'ctype', 'intype', 'tr', 'wadd',
                  'kadd', 'kp', 'kri', 'wc', 'wo', 'tup', 'tlw', 'outmax',
                  'outmin', 'note']
    )
